### ISSUE TITLE
Switches conflict with toggling of machines

### ISSUE THREAD

**Issue by OhiraKyou** [cyanobacterium/ElectricAdvantage#13]
Examine [this album](http://imgur.com/a/UkMJi) of a before and after screenshot featuring a chain consisting of an unlimited electrical power block connected to a switch that, in theory, should control the three mining drills that follow. Notice that, in the second screenshot, in which the switch has been activated, the first drill is off while the others are on.

Currently, machines, such as the mining drill, are disabled by sending a redstone signal. However, switches are _enabled_ with a signal. This inconsistency means that a compact chain of power source > switch > machine > machine fails due to the first machine being disabled by the same redstone signal that enabled the switch.

This can be solved by inverting the switch's state so that it, like machines, is on by default and off when a redstone signal is applied.

Also, I should mention that this likely applies to Steam Advantage as well. And, right-clicking [as the documentation instructs](http://drcyano.wikidot.com/electric-switch) does not toggle the switch.

**Comment by DrPlantabyte** [comment]
Oops, I forgot to edit the documentation (my bad). I had to remove the right-clicking feature because any block update in a neighboring block would trigger a redstone input check, which would then undo the right-click. All machines output a redstone signal (via a comparator) proportional to the number of input items they hold (or their power level for non-inventory machines), so placing a switch next to a machine will cause it to update frequently and making the right-click behavior completely useless in compact builds.

I suppose I could invert the input.

**Comment by DrPlantabyte** [comment]
Next version will have inverted input. Documentation has been updated.
